services:
  everestctl-api:
    image: ghcr.io/vaheed/everestctl-api:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import urllib.request as u; print(u.urlopen('http://localhost:8080/healthz').read())\" >/dev/null 2>&1 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

