name: CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest -q

  deploy:
    needs: test
    runs-on: ubuntu-latest
    env:
      REGISTRY: ${{ secrets.REGISTRY }}
      REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
      REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
      IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to registry
        if: ${{ env.REGISTRY != '' && env.REGISTRY_USERNAME != '' && env.REGISTRY_PASSWORD != '' }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.REGISTRY_USERNAME }}
          password: ${{ env.REGISTRY_PASSWORD }}

      - name: Build image
        run: |
          IMAGE_NAME="${IMAGE_NAME:-everestctl-api}"
          TAG="${{ github.sha }}"
          docker build -t "$IMAGE_NAME:$TAG" .

      - name: Tag with registry
        if: ${{ env.REGISTRY != '' && env.IMAGE_NAME != '' }}
        run: |
          TAG="${{ github.sha }}"
          docker tag "${IMAGE_NAME:-everestctl-api}:$TAG" "${REGISTRY}/${IMAGE_NAME}:$TAG"

      - name: Push image
        if: ${{ env.REGISTRY != '' && env.REGISTRY_USERNAME != '' && env.REGISTRY_PASSWORD != '' && env.IMAGE_NAME != '' }}
        run: |
          docker push "${REGISTRY}/${IMAGE_NAME}:${{ github.sha }}"

      - name: Deploy (placeholder)
        if: ${{ env.REGISTRY != '' && env.IMAGE_NAME != '' && secrets.KUBECONFIG_B64 != '' }}
        run: |
          echo "TODO: add kubectl apply -f manifests here."
          echo "Image: ${REGISTRY}/${IMAGE_NAME}:${{ github.sha }}"
